# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ground_station import freesat_pb2 as ground__station_dot_freesat__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ground_station/freesat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenOrbitLinkGroundStationStub(object):
    """─── OpenOrbitLink Ground Station gRPC Service ───────────────────────────────
    Inspired by Starlink's SXGrpc module architecture.
    Provides telemetry streaming, packet events, and antenna control
    between the Android app and a Raspberry Pi ground station.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/OpenOrbitLink.OpenOrbitLinkGroundStation/GetStatus',
                request_serializer=ground__station_dot_freesat__pb2.StatusRequest.SerializeToString,
                response_deserializer=ground__station_dot_freesat__pb2.StationStatus.FromString,
                _registered_method=True)
        self.GetTelemetry = channel.unary_unary(
                '/OpenOrbitLink.OpenOrbitLinkGroundStation/GetTelemetry',
                request_serializer=ground__station_dot_freesat__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=ground__station_dot_freesat__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.StreamPackets = channel.unary_stream(
                '/OpenOrbitLink.OpenOrbitLinkGroundStation/StreamPackets',
                request_serializer=ground__station_dot_freesat__pb2.PacketStreamRequest.SerializeToString,
                response_deserializer=ground__station_dot_freesat__pb2.PacketEvent.FromString,
                _registered_method=True)
        self.StreamWaterfall = channel.unary_stream(
                '/OpenOrbitLink.OpenOrbitLinkGroundStation/StreamWaterfall',
                request_serializer=ground__station_dot_freesat__pb2.WaterfallRequest.SerializeToString,
                response_deserializer=ground__station_dot_freesat__pb2.WaterfallFrame.FromString,
                _registered_method=True)
        self.ControlAntenna = channel.unary_unary(
                '/OpenOrbitLink.OpenOrbitLinkGroundStation/ControlAntenna',
                request_serializer=ground__station_dot_freesat__pb2.AntennaCommand.SerializeToString,
                response_deserializer=ground__station_dot_freesat__pb2.AntennaResponse.FromString,
                _registered_method=True)
        self.SetFrequency = channel.unary_unary(
                '/OpenOrbitLink.OpenOrbitLinkGroundStation/SetFrequency',
                request_serializer=ground__station_dot_freesat__pb2.FrequencyCommand.SerializeToString,
                response_deserializer=ground__station_dot_freesat__pb2.FrequencyResponse.FromString,
                _registered_method=True)
        self.RunSpeedTest = channel.unary_unary(
                '/OpenOrbitLink.OpenOrbitLinkGroundStation/RunSpeedTest',
                request_serializer=ground__station_dot_freesat__pb2.SpeedTestRequest.SerializeToString,
                response_deserializer=ground__station_dot_freesat__pb2.SpeedTestResult.FromString,
                _registered_method=True)


class OpenOrbitLinkGroundStationServicer(object):
    """─── OpenOrbitLink Ground Station gRPC Service ───────────────────────────────
    Inspired by Starlink's SXGrpc module architecture.
    Provides telemetry streaming, packet events, and antenna control
    between the Android app and a Raspberry Pi ground station.

    """

    def GetStatus(self, request, context):
        """Unary: Get current station status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Unary: Get current telemetry snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPackets(self, request, context):
        """Server streaming: Live decoded packet feed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWaterfall(self, request, context):
        """Server streaming: Live RF waterfall data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlAntenna(self, request, context):
        """Unary: Send antenna control command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFrequency(self, request, context):
        """Unary: Set receiver frequency
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSpeedTest(self, request, context):
        """Unary: Run speed test
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenOrbitLinkGroundStationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=ground__station_dot_freesat__pb2.StatusRequest.FromString,
                    response_serializer=ground__station_dot_freesat__pb2.StationStatus.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=ground__station_dot_freesat__pb2.TelemetryRequest.FromString,
                    response_serializer=ground__station_dot_freesat__pb2.TelemetryResponse.SerializeToString,
            ),
            'StreamPackets': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPackets,
                    request_deserializer=ground__station_dot_freesat__pb2.PacketStreamRequest.FromString,
                    response_serializer=ground__station_dot_freesat__pb2.PacketEvent.SerializeToString,
            ),
            'StreamWaterfall': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWaterfall,
                    request_deserializer=ground__station_dot_freesat__pb2.WaterfallRequest.FromString,
                    response_serializer=ground__station_dot_freesat__pb2.WaterfallFrame.SerializeToString,
            ),
            'ControlAntenna': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlAntenna,
                    request_deserializer=ground__station_dot_freesat__pb2.AntennaCommand.FromString,
                    response_serializer=ground__station_dot_freesat__pb2.AntennaResponse.SerializeToString,
            ),
            'SetFrequency': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFrequency,
                    request_deserializer=ground__station_dot_freesat__pb2.FrequencyCommand.FromString,
                    response_serializer=ground__station_dot_freesat__pb2.FrequencyResponse.SerializeToString,
            ),
            'RunSpeedTest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSpeedTest,
                    request_deserializer=ground__station_dot_freesat__pb2.SpeedTestRequest.FromString,
                    response_serializer=ground__station_dot_freesat__pb2.SpeedTestResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OpenOrbitLink.OpenOrbitLinkGroundStation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OpenOrbitLink.OpenOrbitLinkGroundStation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenOrbitLinkGroundStation(object):
    """─── OpenOrbitLink Ground Station gRPC Service ───────────────────────────────
    Inspired by Starlink's SXGrpc module architecture.
    Provides telemetry streaming, packet events, and antenna control
    between the Android app and a Raspberry Pi ground station.

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OpenOrbitLink.OpenOrbitLinkGroundStation/GetStatus',
            ground__station_dot_freesat__pb2.StatusRequest.SerializeToString,
            ground__station_dot_freesat__pb2.StationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OpenOrbitLink.OpenOrbitLinkGroundStation/GetTelemetry',
            ground__station_dot_freesat__pb2.TelemetryRequest.SerializeToString,
            ground__station_dot_freesat__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPackets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/OpenOrbitLink.OpenOrbitLinkGroundStation/StreamPackets',
            ground__station_dot_freesat__pb2.PacketStreamRequest.SerializeToString,
            ground__station_dot_freesat__pb2.PacketEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWaterfall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/OpenOrbitLink.OpenOrbitLinkGroundStation/StreamWaterfall',
            ground__station_dot_freesat__pb2.WaterfallRequest.SerializeToString,
            ground__station_dot_freesat__pb2.WaterfallFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlAntenna(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OpenOrbitLink.OpenOrbitLinkGroundStation/ControlAntenna',
            ground__station_dot_freesat__pb2.AntennaCommand.SerializeToString,
            ground__station_dot_freesat__pb2.AntennaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFrequency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OpenOrbitLink.OpenOrbitLinkGroundStation/SetFrequency',
            ground__station_dot_freesat__pb2.FrequencyCommand.SerializeToString,
            ground__station_dot_freesat__pb2.FrequencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSpeedTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OpenOrbitLink.OpenOrbitLinkGroundStation/RunSpeedTest',
            ground__station_dot_freesat__pb2.SpeedTestRequest.SerializeToString,
            ground__station_dot_freesat__pb2.SpeedTestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
